### ISSUE TITLE
Line Breaks not escaped

### ISSUE THREAD

**Issue by ghost** [rcdmk/aspJSON#10]
Hi

I am currently using the class in a vbs and have noticed that line breaks in values are not escaped. I work around this by doing the replacement before I pass the values so this is not really a problem for me. 

This might however be an issue only concerning the scripting host, I wanted to inform anyway.

Regards

**Comment by rcdmk** [comment]
I will sure take a look at this.

Thank you!

**Comment by rcdmk** [comment]
This should be fixed now in 3.3.0.
