### ISSUE TITLE
Corrigir o ReadMe

### ISSUE THREAD

**Issue by ghost** [rcdmk/aspJSON#11]
![image](https://cloud.githubusercontent.com/assets/10760131/14865611/c2501b84-0c95-11e6-8edc-6c336bab1329.png)

**Comment by ghost** [comment]
@rcdmk você escreveu `Sting`.
Esta correto ?

**Comment by ghost** [comment]
Mandei um PR com essa correção

**Comment by rcdmk** [comment]
Valeu!
