### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Lamenza** [rcdmk/aspJSON#13]
Good afternoon!

Please, you can use this code in a recordset prepared for paging?

I tried to find a way for it but could not.

I thank you

**Comment by rcdmk** [comment]
Hi.

All you have to do is set the `AbsolutePage` property of the recordset before calling the JSONobject's `LoadRecordset` method.

``` vbs
rs.AbsolutePage = 2 ' here we set the desired page
set jsonArr = json.LoadRecordset(rs) ' we load the recordset page into a JSONArray object
```

**Comment by rcdmk** [comment]
Have this worked for you?
If not, please, provide some feedback and I can help if there is anything broken in the class or your code.
