### ISSUE TITLE
Negative values parsed as positive

### ISSUE THREAD

**Issue by mvlaran** [rcdmk/aspJSON#15]
Hi!

I have an issue: when parsing the following JSON, which has negative numeric values:

`{""item1"":""textvalue"",""item2"":{""subitem1"":{""subitem1subitem1"":-2.3,""subitem1subitem2"":-4.6}},""item3"":""textvalue"",""item4"":""textvalue"",""item5"":""textvalue"",""item6"":{""subitem1"":false,""subitem2"":[]},""item7"":[{""subitem1"":467,""subitem2"":[""arraytextvalue""],""subitem3"":""textvalue"",""subitem4"":700}],""item8"":""textvalue"",""item9"":4.4,""item10"":""textvalue"",""item11"":[""arraytextvalue1"",""arraytextvalue2"",""arraytextvalue3""]}`

It is parsing the negative values as positive values:

`
Open value for "subitem1subitem1"
Open numeric value
Close numeric value: 2.3
Value converted to number
Value added: "subitem1subitem1"
...
Open value for "subitem1subitem2"
Open numeric value
Close numeric value: 4.6
Value converted to number
Value added: "subitem1subitem2"
`

I have made the following change in the code, in the line 290:

`if prevchar = "-" then
  value = prevchar & char
else 
  value = char
end if`

And that seems to resolve it, but you should take a better look into it.

Thanks

**Comment by rcdmk** [comment]
Hi.
Thank you for your suggestion.
I should take a look at this soon.
