### ISSUE TITLE
Loop through Properties

### ISSUE THREAD

**Issue by tbett** [rcdmk/aspJSON#20]
How do you loop through the available (unknown) properties to retrieve the property name and associated value ...

string = [{"prop1":"value1", "prop2":"value2", "prop3":"value3"}]

Thank you!

**Comment by rcdmk** [comment]
The JSONobject class has a property named `pairs` that let's you access directly the property pairs.

``` asp
<%
dim props, prop
props = json.pairs

for each prop in props
    response.write prop.name & ":" & prop.value & "<br>"
next
%>
```

**Comment by tbett** [comment]
So, just to be complete for others.  Thanks again!

```
<%
    dim vJson, json, props, prop
    vJson = "{""prop1"":""value1"", ""prop2"":""value2"", ""prop3"":""value3""}"

    set json = new JSONobject
    json.parse(vJson)

    props = json.pairs
    for each prop in props
        response.write prop.name & " : " & prop.value & "<br>"
    next
%>
```

**Comment by erayuan** [comment]
I get error while 
    vJson = "[{""prop1"":""value1"", ""prop2"":""value2"", ""prop3"":""value3""}]"

Could you give a sample for loop the Json like 
    vJson = "[{""prop1"":""value1"", ""prop2"":""value2"", ""prop3"":""value3""},{""prop1"":""value10"", ""prop2"":""value20"", ""prop3"":""value30""}]"

I receive a Json like this and need to put them in database. Thank you.
