### ISSUE TITLE
Serialize Bug

### ISSUE THREAD

**Issue by ezzatelbadrawy** [rcdmk/aspJSON#21]
Hi,

I use ' JSON object class 3.4.1 - May, 29th - 2016

And I got this error when call varJSON.Serialize() method:

Microsoft VBScript runtime error '800a01b6'

Object doesn't support this property or method: 'obj.pairs'

/jsonObject.class.asp, line 618

Thanks

**Comment by rcdmk** [comment]
Hi.
Can you please give me some example string to pares, so I can reproduce the error in my local enviroment?

It seems to me its a peculiar case.

**Comment by ezzatelbadrawy** [comment]
Hi,

After long time from this debugging this issue I found it occur on this case:
Dim varJSON1
Set varJSON1 = New JSONobject
varJSON1.Add "action", Request("action")

But if but the request on variable and add the variable it success:
Dim varJSON1, varAction
Set varJSON1 = New JSONobject
varAction = Request("action")
varJSON1.Add "action", varAction 

I hope this help you to fix this issue

Thanks

**Comment by rcdmk** [comment]
Thanks. This is a clue of the real problem.
I should take a look at this before sunday.
