### ISSUE TITLE
Remove quotes when needed

### ISSUE THREAD

**Issue by RaviRamDhali** [rcdmk/aspJSON#26]
Is it possible to have an option to remove the quotes from the value object when needed

```
' instantiate the class
dim eachJson
set eachJson = New JSONobject
' add properties
eachJson.Add "coordinates", getCoorFromDatabase
```

Current coordinates values Output (with quotes)
**"49.31184267863867,-121.4249459505081"**
```
{"label":[{"coordinates":"49.31184267863867,-121.4249459505081","title":"Cove"}]}

```

Expected coordinates values Output (without quotes)
**49.31184267863867,-121.4249459505081**

```
{"label":[{"coordinates":49.31184267863867,-121.4249459505081,"title":"Cove"}]}
```

**Comment by RaviRamDhali** [comment]
I got it working .. Parse object into array

```
Dim outputObj
set outputObj = eachJson.parse(getCoorFromDatabase)

eachJson.Add "coordinates", outputObj
```

**Comment by rcdmk** [comment]
Hi. I'm glad you found the solution. ;-)
