### ISSUE TITLE
Drive limitation

### ISSUE THREAD

**Issue by diggybob** [rcdmk/aspJSON#33]
Hello, is it possible to restrict file browsing by drive or folder? EG disallow navigating to C Drive etc. or beyond a named folder?

**Comment by rcdmk** [comment]
Hi.

I'm not sure about what are you talking about.
This project doesn't do with paths.

Can you be more specific, and maybe provide a code sample, so I can help you?

**Comment by diggybob** [comment]
Hi Ricardo

Thanks for your reply!

Something went wrong on GitHub I think, I was enquiring about this post...

https://github.com/windylea/simple-asp-file-manager <https://github.com/windylea/simple-asp-file-manager>

I have no idea how my question was directed to you.

Sorry for the confusion but thanks again for letting me know.

Regards

Bob Wood

**Comment by rcdmk** [comment]
Oh, not a problem.

Best.
