### ISSUE TITLE
how can I loop a JSON?

### ISSUE THREAD

**Issue by erayuan** [rcdmk/aspJSON#34]
Could you give a sample for loop the Json like
[{"prop1":"value1", "prop2":"value2", "prop3":"value3"},{"prop1":"value10", "prop2":"value20", "prop3":"value30"}]

I receive a Json like this and need to loop and put them in database. Thank you.

**Comment by erayuan** [comment]
I found the way, must Parse them to be JSONArray.

**Comment by rcdmk** [comment]
Oh, sorry for the late response.
I'm glad you made it.
