### ISSUE TITLE
DeSerialize in .NET 

### ISSUE THREAD

**Issue by zharris6** [rcdmk/aspJSON#38]
Can anyone provide a sample JSON string that they are able to deserialize in a .net based library?

I have tried using Newtonsoft.Json Json.Deserialize object method, with no luck.

I have tried tons of different combinations on both the Classic ASP and C# side, but none seem to deserialize correctly.

I am sure it is something small. 

I would greatly appreciate any help.

**Comment by zharris6** [comment]
I was able to sort it out by using a Json Array.

**Comment by rcdmk** [comment]
Hi. Sorry for the delay.
It's nice to see you've already sorted it out.
