### ISSUE TITLE
cannot convert 0E-8 to 0

### ISSUE THREAD

**Issue by siliconbase** [rcdmk/aspJSON#43]
hi,

the payment service provider returns a json string and I'm parsing it using aspJSON but the value "blockageRateAmountSubMerchant":0E-8 

cannot be converted to 0.

the debug output is:

New key
Open key
Close key: "blockageRateAmountSubMerchant"
Open value for "blockageRateAmountSubMerchant"
Open numeric value
Close numeric value: 0E
Value converted to 0E
Microsoft VBScript compilation error '800a0407'

Invalid number

/pos/iyzico3/jsonObject.class.asp, line 370

**Comment by rcdmk** [comment]
Hi,
Thanks for highlighting this.

I'll take a look at this ASAP.
