### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by JoseDevelopers** [rcdmk/aspJSON#49]
I would like to know if there is the possibility of coding special characters such as "ñ" or "'". I have reviewed the documentation but I do not found this possibility.

**Comment by rcdmk** [comment]
Hi. This tool doesn't care what characterset you use, although some special characters like double quotes and linebreaks are escaped in the output.
Characters with diacritics are not escaped or encoded because it is an application specific requirement.

**Comment by JoseDevelopers** [comment]
Hi, thanks for your answer. I understand what you say, but for example the character "BS" (8 of the ascii table) gives me an error in the JSON, what can I do with this?
I'm using the "LoadRecordset" method, so I can not clean the string before converting it to JSON, I do not know if I explain ... = (

Thanks for your help!

**Comment by rcdmk** [comment]
Oh. I see what you are saying.
This is one of the special cases I have to escape.
I should fix this soon.

**Comment by JoseDevelopers** [comment]
Great! I will wait for your fix with hope! jeje 

Thank you very much.

**Comment by JoseDevelopers** [comment]
Thanks Ricardo, I'll try it tomorrow.
