### ISSUE TITLE
LCID

### ISSUE THREAD

**Issue by aquilatrindade** [rcdmk/aspJSON#52]
Amigo, o LCID Português Brasileiro é 1046 e não 1043. Só para corrigir, pode confundir alguém com menos experiência.

**Comment by rcdmk** [comment]
Ok.
Vou verificar e, se necessário, atualizar o código.
Obrigado.

**Comment by flameward** [comment]
Oh, God, I was very confused when searched fo my region LCID. Here Portuguese is 1043, when I search - it is 1046. I guess, someone also encountered such porblem ))

**Comment by rcdmk** [comment]
Hi.
Working on that soon.
Thanks.
