### ISSUE TITLE
Como interpretar um array dentro do objeto JSON?

### ISSUE THREAD

**Issue by FabioNani** [rcdmk/aspJSON#54]
Olá Ricardo. 

Primeiramente parabéns pelo seu trabalho. O aspJSON é brilhante e reforça a praticidade que temos em trabalhar com ASP clássico!  É Muito bom ver um Brasileiro fazendo a diferença por aqui.

Estou com uma dúvida aparentemente "banal". 

Preciso coletar o resultado de uma tag "error" que está dentro de um array do meu JSON.
> JSON

`{"multicast_id":6061972918060554697,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidRegistration"}]}`

> ASP
```
                        Response.LCID = 1043 	
			Dim jsonString
			jsonString = objXmlHttp.ResponseText
			Dim jsonObj, outputObj
			set jsonObj = new JSONobject
			set outputObj = jsonObj.parse(jsonString)
			response.write("OK : " & outputObj("success") & "<br>")
			response.write("BUG : " & outputObj("failure"))
			if(outputObj("failure") <> "0") Then
                                'tudo funciona exceto este "error"
				response.write("ERRO : " & outputObj("error")) 
			end if
```

Ops... Desculpe ter postado em PT-BR... Edito para Inglês se preciso for.
Abraço!

**Comment by rcdmk** [comment]
Olá Fábio. Muito obrigado.

Eu prefiro que postem em inglês pra ajudar o maior número de pessoas, mas vamos lá.

A propriedade results é um array e é convertida para um objeto jsonArray, que tem métodos para retornar os valores internos:

```vb
Set errors = outputObj("result")
For Each err In errors
    Response.Write err("error") & "<br>"
Next
```

**Comment by rcdmk** [comment]
Olá. Isso resolveu o seu problema?

**Comment by rcdmk** [comment]
Caso ainda tenha dúvidas, podemos continuar aqui.
