### ISSUE TITLE
Loop in item json

### ISSUE THREAD

**Issue by thomaswpp** [rcdmk/aspJSON#55]
Olá, estou tentando de diversas forma iterar os items de um json para poder inserir em um banco
O json abaixo pode ou ter o events, eu adicionei o events para tentar outra forma, mas normalmente vem apenas o array começando direto com [{"img": ...,, exemplo abaixo com a tag events:

`{"events":[{"img":"https://s3-us-west-2.amazonaws.com/pixel-solutions/event/cover/small/ab080fe968cc82b068fa79dedabe8d1c.png","link":"https://blacktag.com.br/eventos/1891/segue-o-baile","id":3,"name":"Segue o Baile - Lan�amento das As 5 mais e Alforria","hour":"17:00","date":"24/02/2018","local":"Haras Clube Do Cavalo","address":"Avenida Leonor Furlaneto Delgado, 3, 37710-300, Jardim Philad�lphia, Po�os de Caldas, MG","city":"Po�os de Caldas","state":"MG","info":"","_type":"BlacktagItem"}]}`

e sem a tag events, a que for mais fácil:

`[{"img":"https://s3-us-west-2.amazonaws.com/pixel-solutions/event/cover/small/ab080fe968cc82b068fa79dedabe8d1c.png","link":"https://blacktag.com.br/eventos/1891/segue-o-baile","id":3,"name":"Segue o Baile - Lan�amento das As 5 mais e Alforria","hour":"17:00","date":"24/02/2018","local":"Haras Clube Do Cavalo","address":"Avenida Leonor Furlaneto Delgado, 3, 37710-300, Jardim Philad�lphia, Po�os de Caldas, MG","city":"Po�os de Caldas","state":"MG","info":"","_type":"BlacktagItem"}]`

Tentei muitas formas, sem sucesso
Algumas delas são

`set outputObj = jsonObj.parse(jsonString)

            set eventos = outputObj("events")

            for each evento in eventos
                response.write evento("name") & "<br/>"
            next
`

Esta forma com jsonarray ele imprimi todos os items de uma vez, não consegui iterar para imprimir o item que eu desejo

`            
jsonArr.Push jsonObj

            for each i in JSONarr.items

                if isObject(i) and typeName(i) = "JSONobject" then
                    i.write()
                else
                   response.write i("name")
                end if
                
                response.write "<br>"
            next
`

**Comment by rcdmk** [comment]
Hi!

Quase lá!
Como arrays são convertidos para objetos jsonArray, os elementos do array tem que ser acessados pela propriedade "items".

```vb
Set eventos = outputObj("events")

For evento in eventos.items
    Response.Write evento("name") & "<br>"
Next
```

**Comment by rcdmk** [comment]
Hi!
Has this solved your issue?

**Comment by thomaswpp** [comment]
Yes, sorry for the delay. Thank You..

**Comment by rcdmk** [comment]
Glad to help!
