### ISSUE TITLE
How do I remove the brackets []?

### ISSUE THREAD

**Issue by eomonteiro** [rcdmk/aspJSON#58]
I would like to know how to remove the brackets in JSONarray, since I thank you

**Comment by rcdmk** [comment]
The brackets are the JSON representation of an array.
If you have only a single object inside the brackets, you can get it through the `items` property:
```vb
Set jsonArrayObject = json.Parse(jsonArrString)
Set myObject = jsonArrayObject.items(0)
Response.Write myObject("my_property")
```
