### ISSUE TITLE
Type mismatch: 'char'

### ISSUE THREAD

**Issue by nuclearsiloman** [rcdmk/aspJSON#59]
Hi, I've used your parser before without any issues but I'm scratching my head on this one.  I have LCID=1033 and the query below runs fine by itself.

    set JSON = New JSONobject
    query="SELECT top(1) TABLE_NAME FROM db1.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' order by table_name asc"
    set connTemp = server.createobject("adodb.connection")
    connTemp.Open scDSN  
    set rs=server.CreateObject("ADODB.RecordSet")
    set rs=connTemp.execute(query)
    JSON.LoadRecordset rs
   set rs=nothing
    response.clear()
    JSON.Write()

I get: 
Microsoft VBScript runtime error '800a000d'
Type mismatch: 'char'
/store/boomerrang/jsonObject.class.asp, line 915

What do you think the issue may be?

**Comment by nuclearsiloman** [comment]
If I comment out:  'result = replace(result, char(8), "\t") works beautifully!  Of course I don't want to do that though....

**Comment by rcdmk** [comment]
Hi. 
I've introduced this bug in the current release. Sorry.

A fix is already ongoing. I will publish it soon.

**Comment by nuclearsiloman** [comment]
Ah thanks!  I'll keep an eye out for it.  Great work.

**Comment by rcdmk** [comment]
This is fixed with #56.

Thanks.
