### ISSUE TITLE
Using Gitflow in this project?

### ISSUE THREAD

**Issue by MarcoMiltenburg** [rcdmk/aspJSON#63]
From the naming of branches I assume Gitflow is used in this project. But it looks like it's not used correctly / consistently. For example I see no `release` branches. This might look like overkill it does have a purpose.

For example now the `develop` branch is never up-to-date with the latest released version number. In a regular Gitflow workflow you bump the version number in a `release` branch and merge that to `master` AND `develop` when it's released.

Also some of the smaller bugfixes should actually be created in a `hotfix` branch from `master` and upon release be merged into `master` AND `develop` and possibly a `release` branch if one is active at that moment. I sometimes cheat here by continuing an older `release` branch and fixing it in that same branch (which is then called for example `release/3.6.x`) , bumping the patch version number (i.e. the last part of the version, see [Semantic Versioning](https://semver.org/)) and release that by merging again to `master` and `develop`.

And please set the repository's default branch to `develop` instead of `master` as that is the main development branch.

**Comment by rcdmk** [comment]
Hi. I appreciate your desire to help.
I do know and follow git flow in many real life projects that deserve this kind of control.
This project is simple enough to justify only two branches in what I call a simplified git flow.
The master branch is the current release, stable and tested code, while the develop branch is the work in progress branch.

We have only a single code file. Ok, we could split each class in its own file, but even then we would have 3 small files.

I got your point, but I can't see this project growing beyond one more class for raw values and this structure seems fine to me.

I'm happy to receive any feedback and contribution.

Thank you.

**Comment by MarcoMiltenburg** [comment]
Yes, sure, I understand. I only found it a bit confusing to see that the version in the `develop` branch was lower than the currently released version in the `master` branch.

There's really no need to split the file by class. I would even say that would make it even harder to use. Now it's a single file drop-in library that you can use which makes it much easier to use.

**Comment by rcdmk** [comment]
Ok. So I'll make sure to merge back the master branch into develop after releasing and this should avoid that issue.
