### ISSUE TITLE
Bad Data For Date

### ISSUE THREAD

**Issue by smkoder** [rcdmk/aspJSON#66]
When writing an object containing a date, it results in bad JSON data (missing closing quotation after the date)

For example, if I have the following simple ASP code:

` 
    set json = new JSONobject
    set rs = Server.CreateObject("ADODB.recordset")
	query =         "SELECT getdate() AS now_date"
	
    set rs = Server.CreateObject("ADODB.recordset")
    rs.Open query, conn
    json.add "now_date", rs("now_date")
    rs.Close
    json.Write()
`

The following gets written to the stream:

`{"now_date":"2018-04-17T01:25:17}`

Line 697 in version 3.7.0 needs to be updated to add the closing quote to the output

**Comment by greydmar** [comment]
I´ve found same problem.
Closing quotes resolved that issue

**Comment by rcdmk** [comment]
Hello!

Thanks for notifying me.
I'll get back to this project in this weekend.

**Comment by rcdmk** [comment]
Also, feel free to open pull requests to the development branch if you want to. This way I can review and integrate changes fast and you will be listed in the contributors list.

**Comment by rcdmk** [comment]
Fixed in new version [3.8.0](https://github.com/rcdmk/aspJSON/releases/tag/3.8.0).
