### ISSUE TITLE
Inrorrect JSON element removal

### ISSUE THREAD

**Issue by VNexsus** [rcdmk/aspJSON#70]
Line 849: 		redim preserve arr(upperBound)

should be:
		redim preserve arr(upperBound-1)

**Comment by rcdmk** [comment]
Hi.
I should take a look at this soon.

Thanks for pointing out.

**Comment by VNexsus** [comment]
This bug makes json unusable because it doubles the last key-value pair. Since then resulting json becomes invalid, i.e. it cannot be reloaded with Parse() method.
