### ISSUE TITLE
Please put URL in Readme or code comment

### ISSUE THREAD

**Issue by strider72** [rcdmk/aspJSON#73]
I downloaded this a year or so ago and used it.  Some time later I wanted to look for an update, but the GitHub URL is nowhere I can find in the files themselves.  There are several ASP/JSON libraries online.  Please put the https://github.com/rcdmk/aspJSON URL in the comments at the head of jsonObject.class.asp , and/or the readme

**Comment by rcdmk** [comment]
Hi. Good idea.
I'll add this in the next releases.
