### ISSUE TITLE
vbBack not a valid ASP/VBScript constant

### ISSUE THREAD

**Issue by strider72** [rcdmk/aspJSON#75]
In the EscapeCharacters function, line 916 or so of the class file, you have this line:

`result = replace(result, vbback, "\b")`

vbback returns an error if Option Explicit is turned on.  It doesn't appear that "vbback" is a valid vbscript constant.  See http://www.powerasp.net/content/new/vbscript-constants.asp

**Comment by rv-rsouza** [comment]
Hi. Don't know what version your are using, but the master branch (3.7) has a private variable to specify that.

Can you check that version?

**Comment by strider72** [comment]
3.6.0 -- latest release

**Comment by strider72** [comment]
Ah, sorry. Should have checked issues resolved after the release... https://github.com/rcdmk/aspJSON/issues/53

Although... the fix cited in that issue doesn't actually fix this.

**Comment by rcdmk** [comment]
Absolutely no problem.
Thanks.
