### ISSUE TITLE
ASP Syntax error "class JSONobject"

### ISSUE THREAD

**Issue by station1inc** [rcdmk/aspJSON#77]
I am new to this and try to use this parser for some ASP/Json script I have on an IIS 8.0 and this is a simple ASP script.

I get a syntax error on the line "class JSONobject"  … I did check the json configuration and everything appears fine. Any other suggestions?

**Comment by rcdmk** [comment]
Hello! 
Do you have classic ASP support enabled in IIS? I've just tested the current version and this error is not present.

**Comment by station1inc** [comment]
Found the problem. I had included the file deep into my code, whereas when I included it on the first line, it worked like a charm.

Many thanks for the quick response. Totally awesome.
