### ISSUE TITLE
Fails to parse object array (even your own example)

### ISSUE THREAD

**Issue by rokdevil** [rcdmk/aspJSON#78]
Unless I'm missing something...
jsonString = "[{ ""strings"" : ""valorTexto"", ""numbers"": 123.456, ""arrays"": [1, ""2"", 3.4, [5, 6, [7, 8]]], ""objects"": { ""prop1"": ""outroTexto"", ""prop2"": [ { ""id"": 1, ""name"": ""item1"" }, { ""id"": 2, ""name"": ""item2"", ""teste"": { ""maisum"": [1, 2, 3] } } ] } }]" 

will fail on:
set js = new JSONObject
js.parse(jsonString)

Output:

<li>Load string: "[{	"strings": "valorTexto",	"numbers": 123.456,	"arrays": [1, "2", 3.4, [5, 6, [7, 8]]],	"objects": {		"prop1": "outroTexto",		"prop2": [{			"id": 1,			"name": "item1"		}, {			"id": 2,			"name": "item2",			"teste": {				"maisum": [1, 2, 3]			}		}]	}}]"</li>
--
  | <li>Enter init</li>
  | <li>Create array<ul></li>
  | <li>Added to parent object</li>
  | <li>Set as root</li>
  | <li>Open object value</li>
  | <li>Enter init</li>
  | <li>Create object<ul></li>
  | <li>Open key</li>
  | <li>Close key: "strings"</li>
  | <li>Open value for "strings"</li>
  | <li>Open string value</li>
  | <li>Close string value: "valorTexto"</li>
  | <li>Value added to array: "strings": valorTexto</li>
  | <li>New value</li>
  | <li>Open string value</li>
  | <li>Close string value: "numbers"</li>
  | <li>Value added to array: "strings": numbers</li>
  | <li>New value</li>
  | <li>Open string value</li>
  | <li>Close string value: "arrays"</li>
  | <li>Value added to array: "strings": arrays</li>
  | <li>New value</li>
  | <li>Open string value</li>
  | <li>Close string value: "2"</li>
  | <li>Value added to array: "strings": 2</li>
  | <li>New value</li>
  | <li>Open numeric value</li>
  | <li>Close numeric value: 3.4</li>
  | <li>Value converted to number</li>
  | <li>Value added to array: "strings": 3.4</li>
  | <li>New value</li>
  | <li>Open array value</li>
  | <li>Enter init</li>
  | <li>Create array<ul></li>
  | <li>Added to parent array</li>
  | <li>Open numeric value</li>
  | <li>Close numeric value: 5</li>
  | <li>Value converted to number</li>
  | <li>Value added to array: "strings": 5</li>
  | <li>New value</li>
  | <li>Open numeric value</li>
  | <li>Close numeric value: 6</li>
  | <li>Value converted to number</li>
  | <li>Value added to array: "strings": 6</li>
  | <li>New value</li>
  | <li>Open array value</li>
  | <li>Enter init</li>
  | <li>Create array<ul></li>
  | <li>Added to parent array</li>
  | <li>Open numeric value</li>
  | <li>Close numeric value: 7</li>
  | <li>Value converted to number</li>
  | <li>Value added to array: "strings": 7</li>
  | <li>New value</li>
  | <li>Open numeric value</li>
  | <li>Close numeric value: 8</li>
  | <li>Value converted to number</li>
  | <li>Value added to array: "strings": 8</li>
  | <li>Close array</ul></li>
  | <li>Close array</ul></li>
  | <li>Close array</ul></li>
  | <li>New key</li>
  | <li>Open key</li>
  | <li>Close key: "objects"</li>
  | <li>Open value for "objects"</li>
  | <li>Open object value</li>
  | <li>Enter init</li>
  | <li>Create object<ul></li>
  | <li>Added to parent object: "objects"</li>
  | <li>Open key</li>
  | <li>Close key: "prop1"</li>
  | <li>Open value for "prop1"</li>
  | <li>Open string value</li>
  | <li>Close string value: "outroTexto"</li>
  | <li>Value added: "prop1"</li>
  | <li>New key</li>
  | <li>Open key</li>
  | <li>Close key: "prop2"</li>
  | <li>Open value for "prop2"</li>
  | <li>Open array value</li>
  | <li>Enter init</li>
  | <li>Create array<ul></li>
  | <li>Added to parent object</li>
  | <li>Open object value</li>
  | <li>Enter init</li>
  | <li>Create object<ul></li>
  | A property already exists with the name: prop2

**Comment by rcdmk** [comment]
Hi.
Hum... This is strange. I'll check it soon.

Btw, are you running the latest version?

**Comment by wimp1** [comment]
"Me too"!
I have a multirow database table dumped on me as JSON, and your code sees the first column "Id" twice and stops.
I like the rest of it, though. But most of all I'd like something to put the JSON table into a database table. 

I see that the propertynames are stored in the array i_properties in JSONobject.
This requires that each table row (with of course repeated property names) be a separate JSONobject with its own i_properties array, though the parsing is a JSONobject method, not a jsonArray method, so maybe it's a "scope" thing. (Hope this helps).

**Comment by rcdmk** [comment]
Hi.
When you parse a JSON array, the resulting object contains a JSON array property that holds each array value. The properties array is specific for each object and should work as expected, unless you have invalid JSON with repeated property names in a single object.
Can you share a simple copy or example of what you are trying to parse?

**Comment by rcdmk** [comment]
Also, can you please try older versions to see if this works?
I'm suspecting this was introduced in one of  the last 5 releases.
