### ISSUE TITLE
empty objects

### ISSUE THREAD

**Issue by galatechnology** [rcdmk/aspJSON#9]
I have some json objects which can contain empty objects:
e.g.
`{"emptyObjects":{},"objects":{"prop1":"outroTexto","prop2":"bla"}}`

calling jsonObj.Serialize() will give the following output:
`{"emptyObjects":{"objects":{"prop1":"outroTexto","prop2":"bla"}}}`

as you can see, it thinks objects is a child of emptyObjects

**Comment by rcdmk** [comment]
Can you confirm what version are you using, please?
In some point in time I've fixed a similar problem.

As soon I'm back at home I should take a look at this.

**Comment by galatechnology** [comment]
Hi,
I am using the latest version (can't remember what number it is), but I only downloaded it a few days ago

Sent from Outlook Mobilehttps://aka.ms/blhgte

On Wed, Apr 6, 2016 at 8:50 AM -0700, "RCDMK" <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you confirm what version are you using, please?
In some point in time I've fixed a similar problem.

As soon I'm back at home I should take a look at this.

##

**Comment by rcdmk** [comment]
Sorry for the late fix. It's now working as it's supposed to do.
