### ISSUE TITLE
JSON works on React?

### ISSUE THREAD

**Issue by DQ318** [rcdmk/aspJSON#93]
Hi @rcdmk !

I found your repo accidentally when looking for ASP + REACT tutorials.

Sorry to open a new topic just for that but I didn't find an answer in the others that are closed.

My question is: Your code is used to retrieve data from a database and convert it to JSON so that it can be read by Javascript. Can this JSON be used in a project created in React normally?

I ask this because I have an old site and I'm redoing it with a more modern UI (that's why React) and I would like to keep the ASP Classic backend.

Thank you for your attention.

**Comment by rcdmk** [comment]
Hi @DQ318,

This project is a tool to parse and generate JSON and includes utility methods to make using it with DB data easier.

It should work without problems with anything that parses JSON, as it generates valid JSON outputs, including all kinds of client-side JavaScript frameworks and libraries. :-)

Best,
Ricardo

**Comment by dtrillo** [comment]
Yes, it should work!
I use it with VueJS
