### ISSUE TITLE
Extended quote characters are converted to other characters

### ISSUE THREAD

**Issue by devmuch** [rcdmk/aspJSON#98]
I'm having an issue with the ASP function converting characters.

There is a text field in the database containing the string below: 
`quotes - ‘""”“`

When it is loaded/serialized it is getting turned into:
` quotes - â€˜""â€â€œ`

The encoding of the database is `SQL_Latin1_General_CP1_CI_AS`

`Response.LCID = 1033 `

```
Set userProfile = New JSONObject
userProfile.LoadRecordset(rst)
Response.Write("window.userProfile=" & userProfile.Serialize & vbCrLf)
```

The web pages use:
 `<meta charset="windows-1252">`

Any help is appreciated!

**Comment by rcdmk** [comment]
Hi!

That's strange. Quote chars shouldn't be causing that behaviour.
What do you get if you write only that to the response, without serializing?

That looks like invisible characters that got copied from a text editor, like MS Word, and saved into the DB.

I can't reproduce the same issue with those characters, so there must be something else there.

**Comment by rcdmk** [comment]
OK, I could reproduce the issue, but that's not related to aspJSON. That's an encoding issue with the codepage have, that doesn't contain those characters or have different encodings for them.

You can reproduce that by just using `Response.Write` on those strings. Those seem to come from an unicode place.
If you change your charset to unicode, you will be able to see the correct characters.

An alternative is to change your Session.CodePage or Response.CodePage to match your charset with `1252`:

```
Session.CodePage = 1252
' OR
Response.CodePage = 1252
```

Other ways to set that are through your `web.config` file or on IIS settings. You can easily find ways to set the code page or encoding to your environment in Google.

Best,
Ricardo
